'use client'
import {useEffect,useState} from 'react'
const api=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1'
type Project={id:string,name:string,description?:string}
export default function Home(){const [token,setToken]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [projects,setProjects]=useState<Project[]>([]);const [error,setError]=useState(''); const [newProject,setNewProject]=useState('')
 const request=async(path:string,options:RequestInit={})=>{const r=await fetch(api+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(!r.ok)throw new Error((await r.json()).detail||'Request failed');return r.json()}
 useEffect(()=>{const saved=localStorage.getItem('ff-token');if(saved)setToken(saved)},[]);useEffect(()=>{if(token)request('/projects').then(setProjects).catch(e=>setError(e.message))},[token])
 const auth=async(register=false)=>{try{const body=register?{email,password,name}:{email,password};const r=await fetch(api+'/auth/'+(register?'register':'login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.detail);localStorage.setItem('ff-token',data.access_token);setToken(data.access_token);setError('')}catch(e){setError(e instanceof Error?e.message:'Failed')}}
 const create=async()=>{try{const p=await request('/projects',{method:'POST',body:JSON.stringify({name:newProject})});setProjects([p,...projects]);setNewProject('')}catch(e){setError(e instanceof Error?e.message:'Failed')}}
 if(!token)return <main className="min-h-screen grid place-items-center p-6"><section className="card w-full max-w-md"><p className="text-sm text-violet-300">FLAGSHIP</p><h1 className="text-3xl font-bold mt-2">Ship safely, every time.</h1><p className="muted mt-2">Feature flag control for modern engineering teams.</p><div className="space-y-3 mt-8"><input placeholder="Name (for registration)" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password (8+ chars)" value={password} onChange={e=>setPassword(e.target.value)}/><button className="w-full" onClick={()=>auth(false)}>Sign in</button><button className="secondary w-full" onClick={()=>auth(true)}>Create account</button>{error&&<p className="text-red-400 text-sm">{error}</p>}</div></section></main>
 return <main className="min-h-screen md:flex"><aside className="w-full md:w-64 border-b md:border-b-0 md:border-r border-zinc-800 p-6"><div className="font-bold text-xl">FLAGSHIP</div><p className="muted text-sm mt-1">Feature control plane</p><nav className="mt-10 space-y-4 text-sm"><div>Overview</div><div className="muted">Projects</div><div className="muted">API Keys</div><div className="muted">Audit Logs</div></nav></aside><section className="flex-1 p-6 md:p-10 max-w-6xl"><div className="flex justify-between items-start"><div><p className="text-violet-300 text-sm">OVERVIEW</p><h1 className="text-3xl font-bold mt-1">Your projects</h1><p className="muted mt-2">Control releases with confidence.</p></div><button className="secondary" onClick={()=>{localStorage.removeItem('ff-token');setToken('')}}>Sign out</button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-8">{[['Projects',projects.length],['Environments','—'],['Flags','—'],['Enabled','—']].map(([l,v])=><div className="card" key={String(l)}><p className="muted text-sm">{l}</p><p className="text-2xl font-bold mt-2">{v}</p></div>)}</div><div className="card mt-8"><div className="flex gap-3"><input placeholder="New project name" value={newProject} onChange={e=>setNewProject(e.target.value)}/><button disabled={!newProject} onClick={create}>Create project</button></div><div className="mt-6 divide-y divide-zinc-800">{projects.length?projects.map(p=><div className="py-4 flex justify-between" key={p.id}><div><b>{p.name}</b><p className="muted text-sm">{p.description||'No description'}</p></div><span className="muted">Open →</span></div>):<p className="muted py-8 text-center">No projects yet. Create your first feature-flag workspace.</p>}</div>{error&&<p className="text-red-400 text-sm mt-4">{error}</p>}</div></section></main>}
